#sidewise
title: Panting Panda | Ambient Music
email: 
description: 
  Ambient composer panting pandas website.
baseurl: "" 
url: "" 

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
