---
title: Panting Panda
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: 
description: This is the official site of Panting Panda, the moniker of ambient/electronic
  composer Moniet Sawhney.
baseurl: 
url: 
markdown: kramdown
plugins:
- jekyll-feed
- jekyll-seo-tag
sass:
  sass_dir: _scss
  style: compressed
