#sidewise
title: Panting Panda
email:
description:
  This is the official site of Panting Panda, the moniker of ambient/electronic composer Moniet Sawhney.
baseurl: ""
url: ""

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

sass:
  sass_dir: _scss
  style:    compressed
